// Package downloadsession mints and verifies the token that lets the party who spent a download
// keep retrying it while its window is open.
//
// The window used to be identity-free: the providers granted any request that arrived while
// FileMetaData.WindowOpenedAt was recent, so a resource whose allowance was spent stayed freely
// downloadable by anyone holding its link for the whole leeway period. The token is what makes
// the window belong to whoever opened it.
//
// Stateless by design. The server keeps no record of what it has issued, so there is nothing to
// revoke and nothing to migrate: the expiry travels inside the token and the signature is the
// only thing that has to be checked. What that costs is that a token cannot be withdrawn early -
// which is why it is scoped to one resource and dies with the window it was minted for.
package downloadsession

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"strings"

	"github.com/forceu/gokapi/internal/configuration"
)

// ParamName is the query parameter the token travels in. The download link carries it rather
// than a cookie: a cookie cannot reach an external download manager, and being able to hand a
// copied link to one is the case this exists to serve.
const ParamName = "session"

// tokenVersion is carried in the payload so a future format change can be rejected outright
// rather than misread. A token that does not name this version is refused.
const tokenVersion = 1

// payload is what the token asserts. It deliberately holds nothing about the file beyond the id
// already visible in the URL it travels in: no name, no content type, no key material, no nonce,
// no password hash. A token is a permission to retry one download, not a description of it, and
// it ends up in browser history and proxy logs where a description would not belong.
type payload struct {
	Version      int    `json:"v"`
	ResourceType int    `json:"t"`
	ResourceId   string `json:"id"`
	ExpiresAt    int64  `json:"exp"`
}

// Sign returns a token authorising retries of this resource until expiresAt.
func Sign(resourceType int, resourceId string, expiresAt int64) string {
	body, err := json.Marshal(payload{
		Version:      tokenVersion,
		ResourceType: resourceType,
		ResourceId:   resourceId,
		ExpiresAt:    expiresAt,
	})
	if err != nil {
		return ""
	}
	encoded := base64.RawURLEncoding.EncodeToString(body)
	return encoded + "." + base64.RawURLEncoding.EncodeToString(sign(encoded))
}

// Verify reports whether token authorises a retry of this exact resource at time now.
//
// The signature is checked before the payload is parsed, so a forged or corrupt token is never
// decoded. Every failure returns the same false: a caller cannot tell an expired token from a
// forged one from one minted for a different file, and does not need to.
func Verify(token string, resourceType int, resourceId string, now int64) bool {
	encoded, signature, found := strings.Cut(token, ".")
	if !found {
		return false
	}
	expected, err := base64.RawURLEncoding.DecodeString(signature)
	if err != nil {
		return false
	}
	if !hmac.Equal(expected, sign(encoded)) {
		return false
	}
	body, err := base64.RawURLEncoding.DecodeString(encoded)
	if err != nil {
		return false
	}
	var claims payload
	if json.Unmarshal(body, &claims) != nil {
		return false
	}
	return claims.Version == tokenVersion &&
		claims.ResourceType == resourceType &&
		claims.ResourceId == resourceId &&
		claims.ExpiresAt > now
}

// sign is the MAC over the encoded payload. The key is read on every call rather than cached, so
// a key regenerated by configuration.Load is picked up without a restart - the same contract
// storage.DownloadLeeway has with its own setting.
func sign(encoded string) []byte {
	mac := hmac.New(sha256.New, []byte(configuration.Get().DownloadSessionKey))
	mac.Write([]byte(encoded))
	return mac.Sum(nil)
}
