package postgres

import (
	"database/sql"
	"errors"
	"fmt"
	"os"

	"github.com/forceu/gokapi/internal/helper"
	"github.com/forceu/gokapi/internal/models"
	// Required for the postgres driver
	_ "github.com/jackc/pgx/v5/stdlib"
)

// DatabaseProvider contains the database instance
type DatabaseProvider struct {
	postgresDb *sql.DB
}

// DatabaseSchemeVersion contains the version number to be expected from the current database. If lower, an upgrade will be performed
const DatabaseSchemeVersion = 15

// New returns an instance
func New(dbConfig models.DbConnection) (DatabaseProvider, error) {
	return DatabaseProvider{}.init(dbConfig)
}

// GetType returns 2, for being a Postgres interface
func (p DatabaseProvider) GetType() int {
	return 2 // dbabstraction.TypePostgres
}

// Upgrade migrates the DB to a new Gokapi version, if required.
// The Postgres provider was introduced at DatabaseSchemeVersion 15, so every
// Postgres database is created at the current scheme and there is no legacy
// ladder to walk. Databases populated by the migration tool are written through
// the provider interface and are therefore already at the current scheme.
func (p DatabaseProvider) Upgrade(currentDbVersion int) {
	if currentDbVersion > DatabaseSchemeVersion {
		fmt.Printf("Error: Database scheme version is %d, but this Gokapi version only supports up to %d. Please update Gokapi.\n",
			currentDbVersion, DatabaseSchemeVersion)
		osExit(1)
		return
	}
}

// GetDbVersion gets the version number of the database.
// Postgres has no PRAGMA user_version, so the value is kept in a dedicated table.
func (p DatabaseProvider) GetDbVersion() int {
	var version int
	row := p.postgresDb.QueryRow("SELECT Version FROM SchemaVersion WHERE Id = 1")
	err := row.Scan(&version)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return 0
		}
		helper.Check(err)
		return 0
	}
	return version
}

// SetDbVersion sets the version number of the database
func (p DatabaseProvider) SetDbVersion(newVersion int) {
	_, err := p.postgresDb.Exec(`INSERT INTO SchemaVersion (Id, Version) VALUES (1, $1)
					ON CONFLICT (Id) DO UPDATE SET Version = EXCLUDED.Version`, newVersion)
	helper.Check(err)
}

// GetSchemaVersion returns the version number, which the database should be at if fully upgraded
func (p DatabaseProvider) GetSchemaVersion() int {
	return DatabaseSchemeVersion
}

// init connects to the database and creates the table structure, if necessary
func (p DatabaseProvider) init(dbConfig models.DbConnection) (DatabaseProvider, error) {
	if dbConfig.HostUrl == "" {
		return DatabaseProvider{}, errors.New("empty database url was provided")
	}
	if p.postgresDb == nil {
		var err error
		p.postgresDb, err = sql.Open("pgx", dbConfig.HostUrl)
		if err != nil {
			return DatabaseProvider{}, err
		}
		p.postgresDb.SetMaxOpenConns(10)
		p.postgresDb.SetMaxIdleConns(5)

		err = p.postgresDb.Ping()
		if err != nil {
			return DatabaseProvider{}, err
		}
		return p, p.createNewDatabase()
	}
	return p, nil
}

// Close the database connection
func (p DatabaseProvider) Close() {
	if p.postgresDb != nil {
		err := p.postgresDb.Close()
		if err != nil {
			fmt.Println(err)
		}
	}
	p.postgresDb = nil
}

// RunGarbageCollection runs the databases GC
func (p DatabaseProvider) RunGarbageCollection() {
	p.cleanExpiredSessions()
	p.cleanApiKeys()
}

// createNewDatabase creates the table structure if it does not exist yet.
//
// Column order is deliberately identical to the SQLite provider: several queries
// use SELECT * with positional Scan, so reordering columns here would silently
// map values onto the wrong struct fields.
func (p DatabaseProvider) createNewDatabase() error {
	sqlStmt := `CREATE TABLE IF NOT EXISTS ApiKeys (
			Id	TEXT NOT NULL UNIQUE,
			FriendlyName	TEXT NOT NULL,
			LastUsed	BIGINT NOT NULL,
			Permissions	INTEGER NOT NULL DEFAULT 0,
			Expiry	BIGINT,
			IsSystemKey	INTEGER,
			UserId INTEGER NOT NULL,
			PublicId TEXT NOT NULL UNIQUE,
			UploadRequestId	TEXT NOT NULL,
			PRIMARY KEY(Id)
		);
		CREATE TABLE IF NOT EXISTS E2EConfig (
			Id	BIGINT GENERATED BY DEFAULT AS IDENTITY,
			Config	BYTEA NOT NULL,
			UserId INTEGER NOT NULL UNIQUE,
			PRIMARY KEY(Id)
		);
		CREATE TABLE IF NOT EXISTS FileMetaData (
			Id	TEXT NOT NULL UNIQUE,
			Name	TEXT NOT NULL,
			Size	TEXT NOT NULL,
			SHA1	TEXT NOT NULL,
			ExpireAt	BIGINT NOT NULL,
			SizeBytes	BIGINT NOT NULL,
			DownloadsRemaining	BIGINT NOT NULL,
			DownloadCount	BIGINT NOT NULL,
			PasswordHash	TEXT NOT NULL,
			HotlinkId	TEXT NOT NULL,
			ContentType	TEXT NOT NULL,
			AwsBucket	TEXT NOT NULL,
			Encryption	BYTEA NOT NULL,
			UnlimitedDownloads	INTEGER NOT NULL,
			UnlimitedTime	INTEGER NOT NULL,
			UserId	INTEGER NOT NULL,
			UploadDate	BIGINT NOT NULL,
			PendingDeletion	BIGINT NOT NULL,
			UploadRequestId	TEXT NOT NULL,
			PRIMARY KEY(Id)
		);
		CREATE TABLE IF NOT EXISTS Hotlinks (
			Id	TEXT NOT NULL UNIQUE,
			FileId	TEXT NOT NULL UNIQUE,
			PRIMARY KEY(Id)
		);
		CREATE TABLE IF NOT EXISTS Sessions (
			Id	TEXT NOT NULL UNIQUE,
			RenewAt	BIGINT NOT NULL,
			ValidUntil	BIGINT NOT NULL,
			UserId	INTEGER NOT NULL,
			PRIMARY KEY(Id)
		);
		CREATE TABLE IF NOT EXISTS Users (
			Id	INTEGER GENERATED BY DEFAULT AS IDENTITY,
			Name	TEXT NOT NULL UNIQUE,
			Password	TEXT,
			Permissions	BIGINT NOT NULL,
			Userlevel	INTEGER NOT NULL,
			LastOnline	BIGINT NOT NULL DEFAULT 0,
			ResetPassword	INTEGER NOT NULL DEFAULT 0,
			PRIMARY KEY(Id)
		);
		CREATE TABLE IF NOT EXISTS UploadRequests (
			Id	TEXT NOT NULL UNIQUE,
			Name	TEXT,
			UserId	INTEGER NOT NULL,
			Expiry	BIGINT NOT NULL,
			MaxFiles	INTEGER NOT NULL,
			MaxSize	INTEGER NOT NULL,
			Creation	BIGINT NOT NULL,
			ApiKey	TEXT NOT NULL UNIQUE,
			Note	TEXT NOT NULL,
			PRIMARY KEY(Id)
		);
		CREATE TABLE IF NOT EXISTS Statistics (
			Id	INTEGER GENERATED BY DEFAULT AS IDENTITY,
			Type	INTEGER NOT NULL UNIQUE,
			Value	BIGINT,
			PRIMARY KEY(Id)
		);
		CREATE TABLE IF NOT EXISTS SchemaVersion (
			Id	INTEGER NOT NULL,
			Version	INTEGER NOT NULL,
			PRIMARY KEY(Id)
		);`
	err := p.rawPostgres(sqlStmt)
	if err != nil {
		return err
	}
	if p.GetDbVersion() == 0 {
		p.SetDbVersion(DatabaseSchemeVersion)
	}
	return nil
}

// rawPostgres runs a raw SQL statement. Should only be used for creating or upgrading the schema
func (p DatabaseProvider) rawPostgres(statement string) error {
	if p.postgresDb == nil {
		panic("Postgres not initialised")
	}
	_, err := p.postgresDb.Exec(statement)
	return err
}

var osExit = os.Exit
